Attempting to access empty user data after calling read
class cyder.exception.FatalException
Error thrown by line: 554

Stack Trace:

FatalException object, hash=1551639546
	at cyder.utilities.IOUtil.getUserData(IOUtil.java:554)
	at cyder.genesis.CyderMain.lambda$console$2(CyderMain.java:619)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:300)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

