[16-58-17] [EXCEPTION]:
Exception origin: java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
From line: 87
Trace: java.nio.file.FileAlreadyExistsException: C:\Users\Nathan\Documents\IntelliJava\Cyder\logs\2022-02-01.zip
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:231)
at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
at java.base/java.nio.file.Files.createFile(Files.java:640)
at cyder.utilities.OSUtil.zip(OSUtil.java:405)
at cyder.utilities.OSUtil.zip(OSUtil.java:385)
at cyder.handlers.internal.Logger.zipPastLogs(Logger.java:457)
at cyder.handlers.internal.Logger.initialize(Logger.java:283)
at cyder.genesis.Cyder.main(Cyder.java:49)
[16-58-17] [ENTRY]: [Nathan]
[16-58-17] [SYSTEM_IO]: System data pared in IOUtil's static block
[16-58-17] [SYSTEM_IO]: Suggestions pared in IOUtil's static block
[16-58-17] [SYSTEM_IO]: Exit conditions pared in IOUtil's static block
[16-58-17] [SYSTEM_IO]: DebugHashes pared in IOUtil's static block
[16-58-18] [LOGIN]: [CYDER STARTING IN RELEASED MODE]
[16-58-18] [JAVA ARGS]: [LOCATION] [La casa de Nathan]
[17-01-34] [EOL]: Log completed, Cyder crashed unexpectedly: exit code: -200 [External Stop], exceptions thrown: 1
