[22-08-08] [ENTRY]: [Nathan]
[22-08-08] [SYSTEM_IO]: System data pared in IOUtil's static block
[22-08-08] [SYSTEM_IO]: Suggestions pared in IOUtil's static block
[22-08-08] [SYSTEM_IO]: Exit conditions pared in IOUtil's static block
[22-08-08] [SYSTEM_IO]: DebugHashes pared in IOUtil's static block
[22-08-09] [LOGIN]: [AUTOCYPHER ATTEMPT]
[22-08-09] [JAVA ARGS]: [LOCATION] [La casa de Nathan]
[22-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.userJsonDeleted(UserUtil.java:819)
From line: 819
Trace: java.lang.NullPointerException
at cyder.utilities.UserUtil.userJsonDeleted(UserUtil.java:819)
at cyder.utilities.UserUtil.fixUser(UserUtil.java:231)
at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1827)
at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:477)
at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:548)
at cyder.handlers.internal.LoginHandler.determinCyderEntry(LoginHandler.java:424)
at cyder.genesis.Cyder.main(Cyder.java:117)
[22-08-09] [EXCEPTION]:
Exception origin: cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
From line: 123
Trace: java.lang.IllegalArgumentException: File does not exist
at cyder.utilities.UserUtil.setUserData(UserUtil.java:123)
at cyder.ui.ConsoleFrame.setUUID(ConsoleFrame.java:1833)
at cyder.handlers.internal.LoginHandler.recognize(LoginHandler.java:477)
at cyder.handlers.internal.LoginHandler.autoCypher(LoginHandler.java:548)
at cyder.handlers.internal.LoginHandler.determinCyderEntry(LoginHandler.java:424)
at cyder.genesis.Cyder.main(Cyder.java:117)
[22-08-09] [LOGIN]: [AUTOCYPHER FAIL]
[22-10-06] [EOL]: Log completed, Cyder crashed unexpectedly: exit code: -200 [External Stop], exceptions thrown: 2
